# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore CA2V6CP/CA2V6CP/CA2V6CP.csproj
      
    - name: Build
      run: dotnet build CA2V6CP/CA2V6CP/CA2V6CP.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test CA2V6CP/CA2V6CP/CA2V6CP.csproj --no-build --verbosity normal
